# Generated by Django 4.0.6 on 2023-01-13 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Children",
                "verbose_name_plural": "User Children",
            },
        ),
        migrations.CreateModel(
            name="UserChildActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "userChildId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.userchild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child Activities",
                "verbose_name_plural": "Child Activities",
            },
        ),
    ]
