# Generated by Django 4.0.6 on 2023-01-13 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_userchild_userchildactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChildDailyActivy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("hrs", models.IntegerField(default=0)),
                ("mins", models.IntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "childActivityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.userchildactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Child Activities",
                "verbose_name_plural": "Daily Child Activities",
            },
        ),
    ]
