# Generated by Django 4.0.6 on 2023-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_userchilddailyactivy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Sample Activities",
                "verbose_name_plural": "Sample Activities",
            },
        ),
    ]
