# Generated by Django 4.0.6 on 2023-01-13 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_activities"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserChildDailyActivy",
            new_name="UserChildDailyActivity",
        ),
    ]
