# Generated by Django 4.0.6 on 2023-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_rename_userchilddailyactivy_userchilddailyactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchild",
            name="dateOfBirth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
