# Generated by Django 4.1.5 on 2023-01-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0008_activities_childactivity_userchild_childdayacitivity_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChildDayAcitivity",
            new_name="ChildDayActivity",
        ),
    ]
